### ISSUE TITLE
Update for # of triggers

### ISSUE THREAD

**Issue by vadi2** [demonnic/Stressinator#1]
Times reported right now don't account for the number of triggers or patterns that there are, which is a bit of a miss. The new https://wiki.mudlet.org/w/Manual:Lua_Functions#getProfileStats function allows you to get the # of active patterns to see how fast your computer is in the end.

**Comment by demonnic** [comment]
Fixed in https://github.com/demonnic/Stressinator/releases/tag/v2.0.0
